[workspace]
resolver = "2"
members = ["server", "app", "bd-schema"]

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
schema = { path = "./bd-schema" }
